// <auto-generated />
using System;
using AccessibleMicroservicee.Modellayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessibleMicroservicee.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20240127095712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvailabilityMicroservice.Modellayer.Availability", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AvailableDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AvailableTime")
                        .HasColumnType("time");

                    b.HasKey("EmployeeId", "AvailableDate", "AvailableTime");

                    b.ToTable("Availability");
                });
#pragma warning restore 612, 618
        }
    }
}
